// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqyqseumizbrczrtbpxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxeXFzZXVtaXpicmN6cnRicHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTA2NzAsImV4cCI6MjA1ODY4NjY3MH0.YvrknU8cHb6PXoOI9VwKA82oUJaMIgdlqdPTpgdfI84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);