// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtepqpdhescybvmjkvxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0ZXBxcGRoZXNjeWJ2bWprdnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Mjg0NjQsImV4cCI6MjA2MTMwNDQ2NH0.rKUzdSLaCzZnv9-jcBZaNvC5upkf-ex48KSjviyW_V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);